// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NockChat.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NockChat.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527183742_ReplaceTextWithEncryptedPayload")]
    partial class ReplaceTextWithEncryptedPayload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NockChat.Domain.Entities.ChatUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Username")
                        .IsUnique();

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatUserId")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatUserId");

                    b.HasIndex("RoomId", "SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.ParticipantKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatUserId")
                        .HasColumnType("integer");

                    b.Property<string>("EphemeralPublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatUserId")
                        .IsUnique();

                    b.HasIndex("RoomId", "ChatUserId")
                        .IsUnique();

                    b.ToTable("ParticipantKeys");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("InviteCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.ChatUser", b =>
                {
                    b.HasOne("NockChat.Domain.Entities.Room", "Room")
                        .WithMany("ChatUsers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.Message", b =>
                {
                    b.HasOne("NockChat.Domain.Entities.ChatUser", "ChatUser")
                        .WithMany("Messages")
                        .HasForeignKey("ChatUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NockChat.Domain.Entities.Room", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatUser");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.ParticipantKey", b =>
                {
                    b.HasOne("NockChat.Domain.Entities.ChatUser", "ChatUser")
                        .WithOne("ParticipantKey")
                        .HasForeignKey("NockChat.Domain.Entities.ParticipantKey", "ChatUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NockChat.Domain.Entities.Room", "Room")
                        .WithMany("ParticipantKeys")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatUser");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.ChatUser", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ParticipantKey");
                });

            modelBuilder.Entity("NockChat.Domain.Entities.Room", b =>
                {
                    b.Navigation("ChatUsers");

                    b.Navigation("Messages");

                    b.Navigation("ParticipantKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
